### ISSUE TITLE
Editing National Focus Glitch

### ISSUE THREAD

**Issue by DOOMsoldier45** [jordsta95/hoi4-national-focus-maker#1]
After clicking on the national focus to edit it, clicking the X in the focus editor screen removes that focus. It is recoverable by clicking add and submit again but could be a large issue down the road. Included are screenshots of what I am talking about.

Adding focus:
![glitch1](https://cloud.githubusercontent.com/assets/17682849/26563065/8d23be46-449a-11e7-9d9c-b1925d176f82.PNG)

After hitting the X:
![glitch2](https://cloud.githubusercontent.com/assets/17682849/26563066/8f067c58-449a-11e7-9542-7c07ddac62ee.PNG)

I've encountered this bug in Google Chrome only thus far as it is the only browser I use. I will check in Firefox and Edge to see if the issue persists but I have a feeling the problem exists there too. I do not use the tool on Safari as I only develop via Windows.

I am submitting it here as I do not see the issue reported on Reddit as well as to make it public knowledge on how to recover the focus if they run into this issue before a fix can be pushed. I have not tried it with multiple focuses branching off a single one, though.

Suggested fix for developer(s):
- Persist the focus if the editing has been cancelled via the X button with inclusion to the Submit button.

**Comment by jordsta95** [comment]
0.9.2 has just been released to fix this. If you come across any other issues, please let me know 😄
