### ISSUE TITLE
Shit got fucked 1.0

### ISSUE THREAD

**Issue by xDangerRanger** [jordsta95/hoi4-national-focus-maker#11]
The latest change to the code did something bad.....

1) Choose GFX doesn't work for me (Custom GFX does)
2) When I submit a focus it creates 2 focuses, a generic_name focus and the custom focus
3) The Bypass/Available/Reward window pops up, but I cannot choose anything (search function works)

Everything else seems to work fine

**Comment by jordsta95** [comment]
This issue has now been resolved. 

Issue occurred due to the same file being loaded twice, which meant every time you did something, it did it twice.

**Comment by xDangerRanger** [comment]
Yep. Everything works fine again.
Gonna.....eh....close this now...yeah....
