### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [jordsta95/hoi4-national-focus-maker#18]

**Comment by jordsta95** [comment]
Do you have non-ASCII characters used in the titles of your focuses? This is a bug I'm trying to fix, but can't figure why they break to begin with

**Comment by nqpan** [comment]
No I don't. ASCII is just basic Latin letters, right?

**Comment by jordsta95** [comment]
Yep

If you upload it to the server, could you share the password with me, so I can have a look?

**Comment by nqpan** [comment]
ndbw43v3pu

**Comment by jordsta95** [comment]
Hate to disappoint you, but when I imported that, I could export it just fine.

What browser are you using? Do you have any extensions on your browser which block popups? (the downloaded zip opens in a new tab, which some extensions see as a popup, and block)
