### ISSUE TITLE
Add focus button disappears when a focus is erased. 

### ISSUE THREAD

**Issue by Internetismean** [jordsta95/hoi4-national-focus-maker#2]
When an unnamed focus is erased using the delete mode the add focus button disappears, using Google Chrome.

**Comment by jordsta95** [comment]
Is it possible to provide some screenshots, or a step-by-step guide on how you reproduced it+the focus name(s) that were deleted (it is possible, though highly improbable, this may be the cause)

I've just tried to replicate this to no avail, so the more info you could give the better 🙂
