### ISSUE TITLE
Import Data Not Working

### ISSUE THREAD

**Issue by LuxInno** [jordsta95/hoi4-national-focus-maker#3]
I copy pasted the contents of a focus and all it does is display it on the website!

**Comment by jordsta95** [comment]
I'm assuming you mean you are trying to import from an existing focus tree?

If that's the case, you copy the entire focus tree (not just a single focus) into the left text box, and a copy of the localisation file in the right. Then when you press "Import Focus Tree" you will have all focuses in the focus tree appear below
