### ISSUE TITLE
Says I don't have an ID when I do.

### ISSUE THREAD

**Issue by beck0251** [jordsta95/hoi4-national-focus-maker#6]
I tried to export a focus tree with the ID "newfocus" (didn't actually use quotations) but it says I don't have an ID even though I do.

**Comment by beck0251** [comment]
Firefox. I eventually just switched to Google Chrome and it worked fine there.

**Comment by beck0251** [comment]
Also sorry for the late response had a busy day

**Comment by jordsta95** [comment]
After testing in Firefox version 57 (and all versions above) - I have been unable to replicate this issue
