### ISSUE TITLE
When clicking 'export focus' absolutely nothing happens.

### ISSUE THREAD

**Issue by edgarschrub** [jordsta95/hoi4-national-focus-maker#8]
I have produced a focus tree and saved the tree via the server, however now that i have restored the focus and continued on it, the focus tree is no longer exportable as nothing happens when i click the export button. despite this problem, if i was to produce a focus tree from scratch it does allow me to export the focus, this could be a glitch with the software not knowing that a new focus tree has been added from the save file. idk.

**Comment by edgarschrub** [comment]
I am using google chrome, however i tried to use the focus tree creation tool on edge and explorer but no difference.

When referencing the export files i mean this button highlighted in blue.
![image](https://user-images.githubusercontent.com/37668683/37789703-89e0ff72-2dfc-11e8-938d-31696ecd521b.png)

when i click this button, nothing happens at all.

**Comment by edgarschrub** [comment]
mvz3xa8yua

**Comment by jordsta95** [comment]
I've found what the issue is, but I can't fix it right now - Will try to get it done by this time tomorrow though. I don't understand how it's erroring out though, seeing as it will work most of the time, but not sometimes *is very confused*

**Comment by edgarschrub** [comment]
alright, sounds good. thanks for your help mate.

**Comment by jordsta95** [comment]
This issue should now be fixed
